; For updating a release candidate to a beta build, we have to update the
; channel to beta first, and also add the "firefox-mozilla-beta" mar channel id
; to update-settings.ini file. This can be done with the override-update-channel
; parameter under the testrun section.

[testrun]
script=update
allow-mar-channel=firefox-mozilla-beta
channel=beta
target-revision=fb3494d06dfb
target-version=46.0b1#8

[mac 10.9 64bit]
platform=mac
38.0esr=en-US
